server:
  port: 9500
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  profiles:
    active: local
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    mode: HTML
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
